[buildPlans.riosevka]
family = "Riosevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.riosevka.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "flat-hook-serifed"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "flat-bottom-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "straight"
capital-r = "straight-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
c = "serifless"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook-extended"
g = "single-storey-flat-hook-earless-corner"
h = "straight-serifless"
i = "zshaped"
j = "serifless"
k = "symmetric-touching-serifless"
l = "zshaped"
m = "earless-single-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook-short-neck"
u = "toothless-corner-serifless"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
long-s = "bent-hook-serifless"
eszet = "sulzbacher-descending-serifless"
lower-eth = "straight-bar"
lower-thorn = "serifless"
lower-alpha = "crossing"
capital-gamma = "serifless"
capital-delta = "straight"
lower-delta = "flat-top"
lower-iota = "zshaped"
capital-lambda = "straight-serifless"
lower-lambda = "straight"
lower-mu = "toothless-corner-serifless"
lower-xi = "rounded"
lower-chi = "straight-serifless"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ze = "serifless"
cyrl-ze = "serifless"
cyrl-capital-ka = "symmetric-connected-serifless"
cyrl-ka = "symmetric-touching-serifless"
cyrl-el = "straight"
cyrl-em = "flat-bottom-serifless"
cyrl-en = "serifless"
cyrl-capital-u = "straight-serifless"
cyrl-ef = "serifless"
cyrl-che = "standard"
cyrl-yeri = "corner"
cyrl-yery = "corner"
cyrl-capital-ya = "straight-serifless"
cyrl-ya = "straight-serifless"
zero = "slashed"
one = "no-base"
two = "straight-neck"
three = "two-arcs"
four = "closed"
five = "upright-arched"
six = "straight-bar"
seven = "straight-serifless"
eight = "crossing-asymmetric"
nine = "straight-bar"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-mid"
underscore = "high"
caret = "low"
paren = "normal"
brace = "straight"
number-sign = "upright-tall"
ampersand = "closed"
at = "threefold"
dollar = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
pilcrow = "low"
cent = "through"
partial-derivative = "straight-bar"
micro-sign = "toothless-corner-serifless"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.riosevka.variants.italic]
c = "serifless"
f = "flat-hook-tailed"
i = "serifed-diagonal-tailed"
j = "flat-hook-serifless"
l = "serifed-diagonal-tailed"
q = "earless-corner-diagonal-tailed-serifless"
t = "diagonal-tailed-short-neck"
y = "straight-turn-serifless"
long-s = "bent-hook-tailed"
eszet = "sulzbacher-tailed-serifless"
lower-iota = "serifed-diagonal-tailed"
cyrl-el = "tailed"
cyrl-capital-u = "straight-turn-serifless"
cyrl-che = "tailed"

[buildPlans.riosevka.ligations]
inherits = "javascript"


[buildPlans.riosevka-term]
family = "Riosevka Term"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.riosevka-term.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "flat-hook-serifed"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "flat-bottom-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "straight"
capital-r = "straight-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
c = "serifless"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook-extended"
g = "single-storey-flat-hook-earless-corner"
h = "straight-serifless"
i = "zshaped"
j = "serifless"
k = "symmetric-touching-serifless"
l = "zshaped"
m = "earless-single-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook-short-neck"
u = "toothless-corner-serifless"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
long-s = "bent-hook-serifless"
eszet = "sulzbacher-descending-serifless"
lower-eth = "straight-bar"
lower-thorn = "serifless"
lower-alpha = "crossing"
capital-gamma = "serifless"
capital-delta = "straight"
lower-delta = "flat-top"
lower-iota = "zshaped"
capital-lambda = "straight-serifless"
lower-lambda = "straight"
lower-mu = "toothless-corner-serifless"
lower-xi = "rounded"
lower-chi = "straight-serifless"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ze = "serifless"
cyrl-ze = "serifless"
cyrl-capital-ka = "symmetric-connected-serifless"
cyrl-ka = "symmetric-touching-serifless"
cyrl-el = "straight"
cyrl-em = "flat-bottom-serifless"
cyrl-en = "serifless"
cyrl-capital-u = "straight-serifless"
cyrl-ef = "serifless"
cyrl-che = "standard"
cyrl-yeri = "corner"
cyrl-yery = "corner"
cyrl-capital-ya = "straight-serifless"
cyrl-ya = "straight-serifless"
zero = "slashed"
one = "no-base"
two = "straight-neck"
three = "two-arcs"
four = "closed"
five = "upright-arched"
six = "straight-bar"
seven = "straight-serifless"
eight = "crossing-asymmetric"
nine = "straight-bar"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-mid"
underscore = "high"
caret = "low"
paren = "normal"
brace = "straight"
number-sign = "upright-tall"
ampersand = "closed"
at = "threefold"
dollar = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
pilcrow = "low"
cent = "through"
partial-derivative = "straight-bar"
micro-sign = "toothless-corner-serifless"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.riosevka-term.variants.italic]
c = "serifless"
f = "flat-hook-tailed"
i = "serifed-diagonal-tailed"
j = "flat-hook-serifless"
l = "serifed-diagonal-tailed"
q = "earless-corner-diagonal-tailed-serifless"
t = "diagonal-tailed-short-neck"
y = "straight-turn-serifless"
long-s = "bent-hook-tailed"
eszet = "sulzbacher-tailed-serifless"
lower-iota = "serifed-diagonal-tailed"
cyrl-el = "tailed"
cyrl-capital-u = "straight-turn-serifless"
cyrl-che = "tailed"

[buildPlans.riosevka-term.ligations]
# inherits = "javascript"
enables = [
    "center-ops",
    'arrow-l',
    'arrow-r',
    "eqeqeq",
    "eqeq",
    "lteq",
    "exeq",
    "ltgt-diamond-tag",
    "ltgt-slash-tag",
    "slash-asterisk",
    "plusplus",
    "kern-dotty",
    "kern-bars",
    # "llgg", # >> in T<U<V>> is not shift operator
    "llggeq",
    "html-comment",
    "connected-underscore",
    "connected-number-sign",
    "connected-tilde-as-wave",
    "connected-hyphen",
]
